"""Diccionarios que resuelven los codigos de las tablas de la seguridad social"""

# En caso de que algún enlace se haya roto por modificación de la sede de la seguridad social,
# mirar la tabla correspondiente de la URL (*/TXX-NOMBRETABLA.pdf*) en la siguiente URL:
# https://www.seg-social.es/wps/portal/wss/internet/InformacionUtil/5300/1889/39740/3383/3389


# Lista de régimenes
# https://www.seg-social.es/wps/wcm/connect/wss/bcd86052-ad05-42ae-924f-516bdc1bd733/T02-R%C3%A9gimen+Sector+2019-06.pdf?MOD=AJPERES


REGIMEN_SECTOR = {
    "0111": "Régimen General.",
    "0112": "Régimen General. Artistas.",
    "0114": "Régimen General. Profesionales taurinos.",
    "0131": "Régimen General. Sistema especial Resina",
    "0132": (
        "Régimen General. Sistema especial de Frutas, Hortalizas y conservas Vegetales"
    ),
    "0134": (
        "Régimen General. Sistema especial manipulado y empaquetado tomate fresco."
    ),
    "0135": "Régimen General. Sistema especial Industria Hostelera",
    "0136": (
        "Régimen General. Sistema especial trabajadores fijos discontinuos en empresas "
        "de exhibición de cine y salas de bailes, discotecas y salas fiesta"
    ),
    "0137": (
        "Régimen General. Sistema especial de trabajadores discontinuos en empresas de "
        "estudios de mercado y opinión pública."
    ),
    "0138": "Régimen General. Sistema Especial para Empleados de Hogar.",
    "0163": "Régimen General. Sistema Especial Agrario. Actividad en CCC.",
    "0521": "Régimen Especial Trabajadores Autónomos",
    "0613": "Régimen Especial Agrario (Jornadas Reales)",
    "0811": (
        "Régimen Especial de los trabajadores del Mar, Trabajadores por cuenta ajena grupo 1."
    ),
    "0812": (
        "Régimen Especial de los trabajadores del Mar. Trabajadores por cuenta ajena grupo 2A."
    ),
    "0813": (
        "Régimen Especial de los trabajadores del Mar. Trabajadores por cuenta ajena grupo 2B"
    ),
    "0814": (
        "Régimen Especial de los trabajadores del Mar. Trabajadores por cuenta ajena grupo 3."
    ),
    "0821": (
        "Régimen Especial de los trabajadores del Mar. Armadores y asimilados por cuenta ajena "
        "Grupo 1."
    ),
    "0822": (
        "Régimen Especial Trabajadores del Mar. Armadores y asimilados por cuenta ajena Grupo 2A."
    ),
    "0823": (
        "Régimen Especial Trabajadores del Mar. Armadores y asimilados por cuenta ajena Grupo 2B"
    ),
    "0825": "Régimen Especial Trabajadores del Mar. Autónomos",
    "0911": "Minería del carbón",
    "3011": "Asistencia Sanitaria Concertada",
}

# Lista de provincias
# https://www.seg-social.es/wps/wcm/connect/wss/99d52a02-2968-4f38-b594-290ce13c29fb/T62-Provincia.pdf?MOD=AJPERES

PROVINCIAS = {
    "01": "Áraba/Álava",
    "02": "Albacete",
    "03": "Alacant",
    "04": "Almería",
    "05": "Ávila",
    "06": "Badajoz",
    "07": "Illes Balears",
    "08": "Barcelona",
    "09": "Burgos",
    "10": "Cáceres",
    "11": "Cádiz",
    "12": "Castello",
    "13": "Ciudad Real",
    "14": "Córdoba",
    "15": "A Coruña",
    "16": "Cuenca",
    "17": "Girona",
    "18": "Granada",
    "19": "Guadalajara",
    "20": "Guipuzkoa",
    "21": "Huelva",
    "22": "Huesca",
    "23": "Jaén",
    "24": "León",
    "25": "Lleida",
    "26": "La Rioja",
    "27": "Lugo",
    "28": "Madrid",
    "29": "Málaga",
    "30": "Murcia",
    "31": "Navarra",
    "32": "Ourense",
    "33": "Asturias",
    "34": "Palencia",
    "35": "Las Palmas",
    "36": "Pontevedra",
    "37": "Salamanca",
    "38": "Tenerife",
    "39": "Cantabria",
    "40": "Segovia",
    "41": "Sevilla",
    "42": "Soria",
    "43": "Tarragona",
    "44": "Teruel",
    "45": "Toledo",
    "46": "Valencia",
    "47": "Valladolid",
    "48": "Bizcaia",
    "49": "Zamora",
    "50": "Zaragoza",
    "51": "Ceuta",
    "52": "Melilla",
}

# Lista de tipos de id
# https://www.seg-social.es/wps/wcm/connect/wss/b7f8a34b-c589-4982-bf6a-80920c5e55db/T03+-Tipo+de+identificaci%C3%B3n+de+empresario.pdf?MOD=AJPERES

TIPO_IDENTIFICACION = {
    "1": "D.N.I., N.I.F.",
    "6": "Número de Identificación de Extranjero",
    "9": "Código de Identificación Fiscal",
    "K": "Españoles sin DNI menores de 14 años",
    "L": "Españoles sin DNI no residentes",
    "M": "Extranjeros sin NIF no residentes",
}

# Lista codigos paises
# https://www.seg-social.es/wps/wcm/connect/wss/b2a14538-73e9-4e9b-ae81-82e50ec0090b/T12-Nacionalidad+Pais+2021-09.pdf?MOD=AJPERES

PAISES = {
    "004": "AFGANISTAN",
    "008": "ALBANIA",
    "010": "ANTÁRTIDA",
    "012": "ARGELIA",
    "016": "SAMOA AMERICANA",
    "020": "ANDORRA",
    "024": "ANGOLA",
    "028": "ANTIGUA Y BARBUDA",
    "031": "AZERBAYAN",
    "032": "ARGENTINA",
    "036": "AUSTRALIA",
    "040": "AUSTRIA",
    "044": "BAHAMAS",
    "048": "BAHREIN",
    "050": "BANGLADESH",
    "051": "ARMENIA",
    "052": "BARBADOS",
    "056": "BÉLGICA",
    "060": "BERMUDAS",
    "064": "BUTAN",
    "068": "BOLIVIA",
    "070": "BOSNIA-HERZEGOVINA",
    "072": "BOTSWANA",
    "074": "BOUVET (ISLA)",
    "076": "BRASIL",
    "084": "BELICE",
    "086": "OC. INDICO (TERRITORIO BRITÁNICO)",
    "090": "SALOMON (ISLAS)",
    "092": "ISLAS VÍRGENES BRITÁNICAS",
    "096": "BRUNEI DARUSSALAM",
    "100": "BULGARIA",
    "104": "MYANMAR",
    "108": "BURUNDI",
    "112": "BIELORRUSIA",
    "116": "CAMBOYA",
    "120": "CAMERÚN",
    "124": "CANADÁ",
    "132": "CABO VERDE",
    "136": "CAIMANES (ISLAS)",
    "140": "REPÚBLICA CENTROAFRICANA",
    "144": "SRI LANKA",
    "148": "CHAD",
    "152": "CHILE",
    "156": "CHINA",
    "158": "TAIWAN, PROVINCIA DE CHINA",
    "162": "CHRISTMAS (ISLAS)",
    "166": "COCOS (ISLAS)",
    "170": "COLOMBIA",
    "174": "COMORES",
    "175": "MAYOTTE",
    "178": "CONGO",
    "180": "ZAIRE",
    "184": "COOK (ISLAS)",
    "188": "COSTA RICA",
    "191": "CROACIA",
    "192": "CUBA",
    "196": "CHIPRE",
    "203": "REPÚBLICA CHECA",
    "204": "BENIN",
    "208": "DINAMARCA",
    "212": "DOMINICA",
    "214": "DOMINICANA (REPÚBLICA)",
    "218": "ECUADOR",
    "222": "EL SALVADOR",
    "226": "GUINEA ECUATORIAL",
    "231": "ETIOPÍA",
    "232": "ERITREA",
    "233": "ESTONIA",
    "234": "ISLAS FEROE",
    "238": "FALKLAND O MALVINAS",
    "239": "GEORGIA DEL SUR E ISLAS SANDWICH",
    "242": "FIDJI",
    "246": "FINLANDIA",
    "250": "FRANCIA",
    "254": "GUAYANA FRANCESA",
    "258": "POLINESIA FRANCESA",
    "260": "TIERRAS AUSTRALES FRANCESAS",
    "262": "DJIBUTI",
    "266": "GABÓN",
    "268": "GEORGIA",
    "270": "GAMBIA",
    "275": "PALESTINA",
    "276": "ALEMANIA",
    "288": "GHANA",
    "292": "GIBRALTAR",
    "296": "KIRIBATI",
    "300": "GRECIA",
    "304": "GROENLANDIA",
    "308": "GRANADA",
    "312": "GUADALUPE",
    "316": "GUAM",
    "320": "GUATEMALA",
    "324": "GUINEA",
    "328": "GUAYANA",
    "332": "HAITI",
    "334": "HEARD Y MC DONALD (ISLAS)",
    "336": "VATICANO (CIUDAD)",
    "340": "HONDURAS",
    "344": "HONG KONG",
    "348": "HUNGRÍA",
    "352": "ISLANDIA",
    "356": "INDIA",
    "360": "INDONESIA",
    "364": "IRÁN",
    "368": "IRAQ",
    "372": "IRLANDA",
    "376": "ISRAEL",
    "380": "ITALIA",
    "384": "COSTA DE MARFIL",
    "388": "JAMAICA",
    "392": "JAPÓN",
    "398": "KAZAKSTAN",
    "400": "JORDANIA",
    "404": "KENIA",
    "408": "COREA NORTE (REPÚBLICA DEMOCRÁTICA)",
    "410": "COREA SUR (REPÚBLICA)",
    "414": "KUWAIT",
    "417": "KIRGHIZISTAN",
    "418": "LAOS (REPÚBLICA DEMOCRÁTICA POPULAR)",
    "422": "LÍBANO",
    "426": "LESOTHO",
    "428": "LETONIA",
    "430": "LIBERIA",
    "434": "LIBIA (JAMAHIRIYA ÁRABE)",
    "438": "LIECHTENSTEIN",
    "440": "LITUANIA",
    "442": "LUXEMBURGO",
    "446": "MACAO",
    "450": "MADAGASCAR",
    "454": "MALAWI",
    "458": "MALASIA",
    "462": "MALDIVAS (ISLAS)",
    "466": "MALI",
    "470": "MALTA",
    "474": "MARTINICA",
    "478": "MAURITANIA",
    "480": "MAURICIO",
    "484": "MÉJICO",
    "492": "MÓNACO",
    "496": "MONGOLIA",
    "498": "REPÚBLICA DE MOLDAVIA",
    "499": "MONTENEGRO",
    "500": "MONTSERRAT",
    "504": "MARRUECOS",
    "508": "MOZAMBIQUE",
    "512": "OMÁN",
    "516": "NAMIBIA",
    "520": "NAURU",
    "524": "NEPAL",
    "528": "PAÍSES BAJOS",
    "531": "CURAZAO",
    "533": "ARUBA",
    "534": "SINT MARTEEN",
    "535": "BONAIRE, SAINT EAUSTATIUS Y SABA",
    "540": "NUEVA CALEDONIA Y DEPENDENCIAS",
    "548": "VANUATU",
    "554": "NUEVA ZELANDA",
    "558": "NICARAGUA",
    "562": "NÍGER",
    "566": "NIGERIA",
    "570": "NIUE",
    "574": "NORFOLK (ISLA)",
    "578": "NORUEGA",
    "580": "ISLAS MARIANAS DEL NORTE",
    "581": "ISLAS MENORES ALEJADAS E.E.U.U.",
    "583": "MICRONESIA",
    "584": "ISLAS MARSHALL",
    "585": "PALAU",
    "586": "PAKISTAN",
    "591": "PANAMÁ",
    "598": "PAPUA-NUEVA GUINEA",
    "600": "PARAGUAY",
    "604": "PERÚ",
    "608": "FILIPINAS",
    "612": "PITCAIRN",
    "616": "POLONIA",
    "620": "PORTUGAL",
    "624": "GUINEA BISSAU",
    "626": "TIMOR ORIENTAL",
    "630": "PUERTO RICO",
    "634": "QATAR",
    "638": "REUNIÓN",
    "642": "RUMANÍA",
    "643": "FEDERACIÓN DE RUSIA",
    "646": "RUANDA",
    "654": "SANTA HELENA",
    "659": "SAN CRISTÓBAL Y NIEVES",
    "660": "ANGUILA",
    "662": "SANTA LUCÍA",
    "666": "SAN PEDRO Y MIQUELON",
    "670": "SAN VICENTE Y GRANADINAS",
    "674": "SAN MARINO",
    "678": "SANTO TOMÉ Y PRÍNCIPE",
    "682": "ARABIA SAUDÍ",
    "686": "SENEGAL",
    "688": "SERBIA",
    "690": "SEYCHELLES",
    "694": "SIERRA LEONA",
    "702": "SINGAPUR",
    "703": "ESLOVAQUIA",
    "704": "VIETNAM",
    "705": "ESLOVENIA",
    "706": "SOMALIA",
    "710": "REPÚBLICA DE SUDÁFRICA",
    "716": "ZINBABWE",
    "724": "ESPAÑA",
    "728": "SUDÁN DEL SUR",
    "729": "SUDÁN",
    "732": "SAHARA OCCIDENTAL",
    "740": "SURINAM",
    "744": "SVALBARD E ISLA JUAN MAYEN",
    "748": "SWAZILANDIA",
    "752": "SUECIA",
    "756": "SUIZA",
    "760": "SIRIA (REPÚBLICA ÁRABE)",
    "762": "TADJIKISTAN",
    "764": "TAILANDIA",
    "768": "TOGO",
    "772": "TOKELAU",
    "776": "TONGA",
    "780": "TRINIDAD Y TOBAGO",
    "784": "EMIRATOS ÁRABES UNIDOS",
    "788": "TÚNEZ",
    "792": "TURQUÍA",
    "795": "TURKMENISTAN",
    "796": "TURKS Y CAICOS (ISLAS)",
    "798": "TUVALU",
    "800": "UGANDA",
    "804": "UCRANIA",
    "807": "MACEDONIA TERR. ANT. REP. YUGOSLAVA",
    "818": "EGIPTO",
    "826": "REINO UNIDO",
    "831": "GUERNSEY",
    "832": "JERSEY",
    "833": "ISLA DE MAN",
    "834": "REPÚBLICA UNIDA DE TANZANIA",
    "840": "ESTADOS UNIDOS",
    "850": "VÍRGENES DE E.E.U.U (ISLAS)",
    "854": "BURKINA FASO",
    "858": "URUGUAY",
    "860": "UZBEKISTAN",
    "862": "VENEZUELA",
    "876": "WALLIS Y FUTUNA (ISLAS)",
    "882": "SAMOA",
    "887": "YEMEN",
    "894": "ZAMBIA",
    "952": "APÁTRIDAS",
    "953": "PAÍS DESCONOCIDO",
    "954": "DESCONOCIDO SIN CONVENIO",
    "955": "DESCONOCIDO CON CONVENIO",
}

# Lista de codigos de accion
# https://www.seg-social.es/wps/wcm/connect/wss/dad0574d-411d-4d69-b78f-9d7947ceabab/T07-Acci%C3%B3n+2024-02.pdf?MOD=AJPERES

ACCIONES_EMP = {
    "EMP": "Acciones a nivel de Empresa",
    "CU": "Consulta de trabajadores con movimientos previos en un CCC",
    "CS": "Situación de la empresa",
    "CT": "Relación de trabajadores en alta en un CCC",
    "CTA": "Informe de Trabajadores en alta por Autorización",
    "CTP": "Informe de Trabajadores en alta por CCC Principal",
    "CL": "Vida laboral de un CCC",
    "CC": "Certificado de Cotización normal sin detalle de deuda",
    "CC1": "Certificado de Cotización normal con detalle de deuda",
    "CC2": "Certificado de Cotización Contrato del Estado",
    "CC3": "Certificado de Cotización. Artículo 42",
    "NMT": "Número Medio de Trabajadores",
    "PMT": "Plantilla Media de Trabajadores en alta",
    "AAC": "Alta Autorización Certificado artículo 42 Estatuto de los Trabajadores",
    "MAC": "Modificación Autorización Certificado artículo 42 Estatuto de los Trabajadores",
    "PLC": "Informe de datos para la cotización por Período de Liquidación - CCC",
    "PLP": "IDC/PL-CCC por CCC Principal",
    "PLA": "IDC/PL-CCC por Autorización",
    "CRD": "Cumplimiento Reserva Discapacitados",
    "CUP": "Informe de trabajadores con movimientos previos en un CCC, por CCC Principal",
    "CUA": "Informe de trabajadores con movimientos previos en un CCC, por Autorización",
}

ACCIONES_TRA = {
    "MA": "Alta sucesiva",
    "MB": "Baja",
    "MG": "Cambio de grupo de cotización",
    "ME": "Eliminación de movimientos previos",
    "MC": "Cambio de contrato (tipo/coeficiente)",
    "MT": "Cambio de ocupación",
    "MD": "Eliminación de altas consolidadas",
    "MR": "Eliminación de bajas consolidadas",
    "CP": "Consulta de movimientos previos de un afiliado",
    "CH": "Consulta de situación del afiliado en la empresa",
    "CD": "Duplicados de TA2",
    "CA": "Corrección del alta, régimen 0132",
    "CB": "Corrección de la baja, régimen 0132",
    "CCP": "Cambio de Categoría Profesional",
    "CCJ": "Cambio de Coeficiente Reductor de la Edad Jubilación",
    "MJR": "Mecanización de Jornadas Reales (régimen 0163)",
    "MFR": "Modificación Fecha Real del Alta (régimen 0163)",
    "ASA": "Anotación de periodos de situaciones adicionales de afiliación",
    "MSA": "Modificación de periodos de situaciones adicionales de afiliación",
    "ESA": "Eliminación de periodos de situaciones adicionales de afiliación",
    "CJR": "Informe de Jornadas Reales",
    "ASC": "Alta de Subcontratación o Cesión",
    "MSC": "Modificación de Subcontratación o Cesión",
    "ESC": "Eliminación de Subcontratación o Cesión",
    "ACT": "Anotación Convenio Colectivo de trabajador",
    "MCT": "Modificación de Convenio de Trabajador",
    "ECT": "Eliminación de Convenio de Trabajador",
    "ADT": "Anotación de Días Trabajados",
    "EDT": "Eliminación de Días Trabajados",
    "AMC": "Anotación Modalidad de cotización",
    "AIT": "Anotación de Períodos de Incapacidad Temporal",
    "CIT": "Cierre de Períodos de Incapacidad Temporal",
    "EIT": "Eliminación de Períodos de Incapacidad Temporal",
    "IDC": "Informe de Datos para la Cotización",
    "CTO": "Consulta de alta de Trabajadores en Otra empresa",
    "MTE": "Modificación del indicativo número Trabajadores Empresa",
    "MIN": "Mecanización de INactividad",
    "PLT": "Informe de datos para la cotización por Periodo de Liquidación - Trabajador",
    "RLT": "Informe de datos para la cotización por Relación Laboral - Trabajador",
    "ABA": "Anotación en base de datos integrados de Bases Adicionales",
    "MBA": "Modificación en base de datos integrados de Bases Adicionales",
    "EBA": "Eliminación en base de datos integrados de Bases Adicionales",
    "MOC": "Modificación de Ocupación CNO",
    "MDP": "Modificación Días Prácticas",
    "EDP": "Eliminación Días Prácticas",
}

# Lista de Tipos Alfabéticos de Empresarios
# https://www.seg-social.es/wps/wcm/connect/wss/881314b5-d6f3-41ba-a5ce-d1b32aad100c/T08-Tipo+alfab%C3%A9tico+de+Empresario.pdf?MOD=AJPERES

TIPO_AFABETICO_EMPRESARIO = {
    "1": "Individual",
    "2": "Colectivo",
    "3": "Sin personalidad jurídica",
    "4": "Entidad u Organismo de las Admones.Públicas",
}

# Lista de Identificadores de Persona Fisica
# https://www.seg-social.es/wps/wcm/connect/wss/7b8b270c-53e1-4218-835d-c990755c8e0a/T11-Tipo+de+identificador+de+Persona+F%C3%ADsica.pdf?MOD=AJPERES
IPF = {
    "1": "D.N.I. (N.I.F.)",
    "2": "Pasaporte",
    "6": "Numero Identificacion Extranjero",
    "L": "Españoles sin DNI no residentes en España",
    "M": "Extranjeros sin NIE en España",
}

# Lista de tipos de vía
# https://www.seg-social.es/wps/wcm/connect/wss/a803b183-5f9e-4b06-ab99-2e4e99cef8e3/T15-TABLA+DE+TIPO+DE+V%C3%8DA+.pdf?MOD=AJPERES
TIPO_VIA = {
    "AC": "ACERA",
    "AD": "ALDEA",
    "AL": "ALAMEDA",
    "AM": "AMPLIACIÓN",
    "AN": "ANGOSTA",
    "AP": "APARTAMENTOS",
    "AQ": "ACEQUIA",
    "AS": "APARTADO DE CORREOS",
    "AT": "ATAJO",
    "AV": "AVENIDA",
    "BA": "BAJADA",
    "BC": "BARRANCO",
    "BD": "BARRIADA",
    "BL": "BLOQUES",
    "BO": "BARRIO",
    "CA": "CALLEJA",
    "CE": "CALLEJUELA",
    "CH": "CHALET",
    "CJ": "CALLEJÓN",
    "CL": "CALLE",
    "CM": "CAMINO",
    "CN": "COSTANILLA",
    "CO": "COLONIA",
    "CP": "COOPERATIVA",
    "CR": "CARRERA",
    "CS": "CASERIO",
    "CT": "CARRETERA",
    "CU": "CUESTA",
    "CZ": "CALZADA",
    "EA": "ESCALA",
    "ED": "EDIFICIO",
    "EL": "ESCALINATA",
    "ES": "ESCALERA",
    "ET": "ESTRADA",
    "GL": "GLORIETA",
    "GR": "GRUPO",
    "KO": "CORRAL",
    "LG": "LUGAR",
    "LL": "LLANO",
    "MC": "MERCADO",
    "MN": "MUNICIPIO",
    "MO": "MONTAÑA",
    "MZ": "MANZANA",
    "PA": "PASEO ALTO",
    "PB": "POBLADO",
    "PC": "PARTICULAR",
    "PD": "PASADIZO",
    "PE": "PLAZOLETA",
    "PG": "POLÍGONO",
    "PI": "PASILLO",
    "PJ": "PASAJE",
    "PL": "PLACETA",
    "PN": "PROLONGACION",
    "PO": "PASEO BAJO",
    "PP": "PASEO",
    "PQ": "PARQUE",
    "PR": "PORTALES",
    "PS": "PASO",
    "PT": "PATIO",
    "PU": "PLAZUELA",
    "PV": "PRIVADA",
    "PZ": "PLAZA",
    "RA": "RAMAL",
    "RB": "RAMBLA",
    "RC": "RINCONADA",
    "RD": "RONDA",
    "RE": "RESIDENCIA",
    "RL": "RESIDENCIAL",
    "RN": "RINCÓN",
    "RP": "RAMPA",
    "RR": "RIBERA",
    "SC": "SECTOR",
    "SD": "SENDA",
    "SP": "PASSEIG",
    "SR": "SENDERO",
    "SU": "SUBIDA",
    "TL": "TRANSVERSAL",
    "TO": "TORRE",
    "TR": "TRAVESÍA",
    "TS": "TRASERA",
    "TT": "TORRENTE",
    "UR": "URBANIZACIÓN",
    "VI": "VÍA",
    "VL": "VILLAS",
    "VV": "VIVIENDAS",
    "XX": "SIN DATOS DOMICILIARIOS",
    "ZO": "ZONA",
    "ZZ": "OTROS",
}

# Listado de tipos de peculiaridades de cotización
# https://www.seg-social.es/wps/wcm/connect/wss/a445496f-fa27-49ca-afce-6b5d3e687cf7/T49-Tipo+de+peculiaridad+de+cotizaci%C3%B3n+2024-06.pdf?MOD=AJPERES

TIPO_PECULIARIDAD_COTIZACION = {
    "01": "Bonificación INEM",
    "02": "Bonificación Hacienda embarcaciones Zona Especial de Canarias",
    "03": "Reducción",
    "04": "Incremento de tipos",
    "05": "Incremento de cuota",
    "06": "Decremento de tipos",
    "07": "Exoneración",
    "08": "Colaboración",
    "09": "Exclusiones",
    "10": "Decremento de cuotas",
    "11": "Cotización adicional",
    "12": "Reducción a cargo del INEM",
    "13": "Bonificación SPEE Prog Fomento de Empleo-Porcentaje",
    "14": "Diferimiento en el ingreso de cuotas",
    "15": "Exoneración E.R.E. Fuerza mayor. Tiempo parcial",
    "17": "Aportación no obligatoria - Suspensión Regulación Empleo",
    "18": "Aportación no obligatoria - Suspensión Regulación Empleo Parcial",
    "19": "Bonificación SPEE con cargo a Hacienda",
    "20": "Período sin retribución",
    "21": "IT.CC.Pago delegado",
    "22": "IT.CC.Pago directo",
    "23": "IT.AT.Pago delegado",
    "24": "IT.AT.Pago directo",
    "25": "IT.CC.Pago delegado diferido",
    "26": "IT.CC.Pago delegado diferido mes anterior",
    "27": "IT.AT.Pago delegado diferido",
    "28": "IT.AT.Pago delegado diferido mes anterior",
    "29": "IT.CC.Colaboradoras excluidas 15 días",
    "30": "IT.AT.Colaboradoras excluidas",
    "31": "Maternidad/paternidad tiempo completo",
    "32": "Maternidad tiempo parcial",
    "33": "Paternidad tiempo parcial",
    "34": "Riesgo embarazo/lactancia",
    "35": "Funcionarios-permiso sin sueldo",
    "36": "Funcionarios- suspensión provisional",
    "37": "Exoneración E.R.E. Fuerza mayor. Tiempo completo",
    "38": "Moratoria",
    "39": "Decremento BBCC",
    "40": "Tipo cotización especial.SEA",
    "41": "Bonificación Programa Fomento de Empleo. Cuantía diaria",
    "42": "Red. Cuota SS-cuantía",
    "43": "Tarifa plana",
    "44": "Cotización especial solidaridad",
    "45": "Pluriempleo con exclusiones diferentes",
    "46": "Bonificación Sistema Nacionla Garantía Juvenil",
    "47": "Reducción – Cuantía – Sin horas complementarias",
    "48": "Bonificación – Cuantía – Sin horas complementarias",
    "49": "Tipos de cotización AT.EP.",
    "50": "Tarifa plana. Reint. Parcial incumplimiento nivel de empleo",
    "51": "Bonificación SEA transformación en indefinido. Cuantía mensual",
    "52": "Bonificación SEA transformación en indefinido. Cuantía diaria",
    "53": "Régimen Especial Minería del carbón",
    "54": "Bonificación SEA transformación en indefinido. Cuota fija mensual",
    "55": "Bonificación SEA transformación en indefinido. Cuota fija diaria",
    "56": "Cotización adicional contrato temporal inferior a 30 días",
    "57": "Bonificación SEEH.FOGASA 01-10-2022",
    "58": "Reducción Planes de Pensiones Empleo",
    "59": "Contratos Formativos en Alternancia",
    "60": "Exclusión- Prácticas no remuneradas",
}
